### ISSUE TITLE
Running Pyrugga

### ISSUE THREAD

**Issue by pearseod** [jlondal/pyrugga#1]
I am having a few issues running Pyrugga. 

Namely when I run this code

    import pyrugga as pyr
    import matplotlib.pyplot as plt

    df = pyr.Match('irevwal.xml')

    PermissionError: [WinError 32] The process cannot access the file because it is being used by 
    another process: 'd691a25c-3017-4f79-9678-e4f5e0e31321'

Any ideas as to why to this may be happening?

Thanks

**Comment by jlondal** [comment]
You need a super scout file from Opta https://www.optaprorugby.com/ which had the xml files with the data

**Comment by pearseod** [comment]
Yes I the one I have used is a superscout file. I have used the to_df function and got it into a data frame which is great, however it doesnt seem that it works when using pyr.match

**Comment by jlondal** [comment]
So couple of things

1. The error is because you have the SuperScout file open in another program. I had assumed you had got that error because you did not have a file. Check you do not the .xml opened by something else or reset your machine :-) 

2. I have never tested the library on Windows. It runs on OSX and Linux fine. I would think it's unlikely it does not work on Windows though. To be sure use Docker to check if it is a windows issue. 

What Ireland vs. Wales game are you looking at?

**Comment by pearseod** [comment]
Thanks for the Reply, 
The file was not opened by any other program, I had restarted everything as well but to no avail. 

I will take a look at the docker option that you stated. 

Its the Ireland Wales Summer Series 19 Game... 7th Sept....

EDIT
Yeah I have never used Docker or familiar with what it is used for.

**Comment by jlondal** [comment]
Private message me twitter @james_londal and happy to help. 

In the meantime, I have created a Kaggle notebook to help you https://www.kaggle.com/piccolo/wales-vs-ireland-test-pyrugga 

You should be able to clone it and then run the code. Works fine on the game on the 7th this year between Wales and Ireland.

**Comment by pearseod** [comment]
`---------------------------------------------------------------------------
    PermissionError                           Traceback (most recent call last)
    in 
      1 import pyrugga
    ----> 2 pyrugga.Match("irewal.xml")

    C:\ProgramData\Anaconda3\lib\site-packages\pyrugga\match.py in __init__(self, fn_name, zones)
     37         """
     38         (self.events,self.summary,self.players) = to_df(fn_name)
      ---> 39         self._genTimeLine()
      40 
      41         """

    C:\ProgramData\Anaconda3\lib\site-packages\pyrugga\match.py in _genTimeLine(self)
     75         sql = open(os.path.join(d, 'timeline.sql'), 'r').read()
     76 
    ---> 77         os.remove(tmp_filename)
     78 
     79         timeline = pd.io.sql.read_sql(sql,conn)`


The file seems to stopping at this point, is it the actual function keeping the file open and causing the error

**Comment by jlondal** [comment]
This is either a Windows or Anaconda issue. Did you manage to use the Kaggle notebook I sent? That would be the simplest solution. 

Failing that I can I will try think of a solution for Windows tonight. 

We all use macs so not a high priority to fix windows specific bugs. 

James

**Comment by jlondal** [comment]
I have updated the README.MD to explain how to run on windows. Not having a windows machine to test on I cannot be 100% sure this will work so let me know how you get along. 

I think the problem is because the library uses SQLite which does not allow multiple processes to use in Windows. It's not a bug so much with Pyrugga as a problem with Anaconda and Windows but cannot be 100% sure.

**Comment by pearseod** [comment]
Hey mate, Appreciate the help but the jupyter server is not opening after running both the _start and _end files. 
Never worry, appreciate the effort. Looks a great package!

**Comment by jlondal** [comment]
Yeah I would suggest looking into how to use Docker or get a Mac ;-) 


James
